# Generated by Django 5.0.6 on 2026-03-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('athmovil', 'ATH Móvil'), ('paypal', 'PayPal'), ('stripe', 'Tarjeta de Crédito/Débito')], default='athmovil', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('athmovil', 'ATH Móvil'), ('paypal', 'PayPal'), ('efectivo', 'Efectivo'), ('stripe', 'Tarjeta de Crédito/Débito')], default='athmovil', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
